### PR TITLE
update zoom to deep-zoom and add annotation tool

### PR DESCRIPTION
**Pull request by konradoo11**
New build process using a bundler like Webpack to import and use OpenLayers to implement DeepZoom functionality and annotation tool.
The following has been changed:
Set Up a New Project Structure
Install Necessary Dependencies
Configure Babel and Webpack
Update the Code to Use OpenLayers v10.2.1
Adjust for Any API Changes in OpenLayers v10
Updated README.md

### CODE REVIEW

**Comment by oeway** [comment]
Hi, the image tiles should be excluded from the source code, you can use .gitignore file.

**Comment by konradoo11** [comment]
> Hi, the image tiles should be excluded from the source code, you can use .gitignore file.

Of course, I will revisit the PR and do so.

**Comment by cccoolll** [comment]
Hi @konradoo11 , please put this folder back and make a commit: https://github.com/aicell-lab/agent-lens/tree/main/scripts

**Review by cccoolll — CHANGES_REQUESTED** [review]
Hi @konradoo11 , please put this folder back and make a commit: https://github.com/aicell-lab/agent-lens/tree/main/scripts

**Comment by cccoolll** [comment]
@konradoo11 There's are conflicts need to be resolved, can you resolve this so I can merge this pull request?

**Pull request closed without merging**
